### ISSUE TITLE
move to depject org?

### ISSUE THREAD

**Issue by dominictarr** [ahdinosaur/depnest#2]
https://github.com/depject

I figured that with [this](https://github.com/depject/depject/pull/24#issuecomment-281959104) now we have 3 modules - that makes a family, so it should be in an org!

**Comment by ahdinosaur** [comment]
woo! done. :tada:

**Comment by ahdinosaur** [comment]
@dominictarr can you make me an org "owner"? churrr. :cat:

**Comment by dominictarr** [comment]
done, I made the others owners too
